email:
  subject: "Assunto Padrão"
  message: "Mensagem Padrão"
spring:
  application:
    name: findpark
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enabled: true
      mail.smtp.starttls.required: true
    templates:
      path: ${MAIL_TEMPLATES_PATH}
  data:
    mongodb:
      uri: mongodb://localhost:27017/findpark
api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}
  web:
    domain: http://localhost:3000
  cors:
    origin: http://localhost:3000,http://localhost:8080

viacep:
  url: ${VIACEP_URL}